use crate::fetcher::{
    arxiv::ArxivPaper, cncf::CNCFProject, huggingface::HFModel, podcast::PodcastEpisode,
    release::ReleaseItem, NewsItem,
};
use crate::llm::LLMClient;
use crate::radar::Blip;
use chrono::Utc;
use serde::Deserialize;
use std::collections::HashMap;

// Encoded prompts generated by build.rs – not human-readable in the binary
mod enc {
    include!(concat!(env!("OUT_DIR"), "/encoded_prompts.rs"));
}

fn decode(data: &[u8]) -> String {
    const KEY: &[u8] = &[
        0x4e, 0x6c, 0x39, 0x21, 0x7f, 0x2a, 0x5c, 0x11, 0x88, 0x45, 0xc3, 0x7b, 0x2d, 0x91, 0xf4,
        0x63,
    ];
    let bytes: Vec<u8> = data
        .iter()
        .enumerate()
        .map(|(i, &b)| b ^ KEY[i % KEY.len()])
        .collect();
    String::from_utf8(bytes).unwrap_or_default()
}

// ── Competitive analysis ───────────────────────────────────────────────────────

#[derive(Debug, Clone, Deserialize)]
pub struct CompetitorRow {
    pub name: String,
    #[serde(rename = "type", default)]
    pub type_: String,
    #[serde(default)]
    pub positioning: String,
    #[serde(default)]
    pub pros: String,
    #[serde(default)]
    pub cons: String,
}

pub struct CompetitionAnalysis {
    pub competitors: Vec<CompetitorRow>,
    pub text: String,
}

fn build_radar_items(target: &Blip, all_blips: &[Blip]) -> String {
    all_blips
        .iter()
        .filter(|b| b.number != target.number)
        .map(|b| {
            let same_q = if b.quadrant == target.quadrant {
                "[同象限] "
            } else {
                ""
            };
            format!(
                "  - {}{} ({}) — {}",
                same_q,
                b.name,
                b.ring.to_uppercase(),
                b.description.chars().take(60).collect::<String>()
            )
        })
        .collect::<Vec<_>>()
        .join("\n")
}

fn strip_code_fence(s: &str) -> &str {
    let s = s.trim();
    let s = if s.starts_with("```") {
        s.split_once('\n').map(|x| x.1).unwrap_or(s)
    } else {
        s
    };
    if s.ends_with("```") {
        s.rsplit_once("```").map(|x| x.0).unwrap_or(s).trim_end()
    } else {
        s
    }
}

pub async fn summarize_one(item: &NewsItem, kw: &str, llm: &LLMClient) -> String {
    let template = if item.source == "GitHub" {
        decode(enc::GITHUB)
    } else {
        decode(enc::NEWS)
    };

    let prompt = template
        .replace("{keyword}", kw)
        .replace("{title}", &item.title)
        .replace("{source}", &item.source)
        .replace("{url}", &item.url)
        .replace("{description}", &item.description);

    llm.invoke(&prompt)
        .await
        .unwrap_or_else(|e| format!("摘要生成失敗: {}", e))
}

pub async fn summarize_arxiv(paper: &ArxivPaper, kw: &str, llm: &LLMClient) -> String {
    let authors = paper.authors.join(", ");
    let categories = paper.categories.join(", ");

    let prompt = decode(enc::ARXIV)
        .replace("{keyword}", kw)
        .replace("{title}", &paper.title)
        .replace("{authors}", &authors)
        .replace("{categories}", &categories)
        .replace("{abstract_text}", &paper.abstract_text);

    llm.invoke(&prompt)
        .await
        .unwrap_or_else(|e| format!("摘要生成失敗: {}", e))
}

pub async fn summarize_cncf_project(project: &CNCFProject, llm: &LLMClient) -> String {
    let maturity_label = match project.maturity.as_str() {
        "graduated" => "已畢業（Graduated）— CNCF 最高成熟度，廣泛用於生產環境",
        "incubating" => "孵化中（Incubating）— 有實際使用案例，快速成長中",
        "sandbox" => "沙箱（Sandbox）— 新興專案，早期採用者值得關注",
        _ => &project.maturity,
    };
    let accepted_str = project
        .accepted_at
        .map(|d| d.format("%Y-%m-%d").to_string())
        .unwrap_or_else(|| "未知".to_string());

    let prompt = decode(enc::CNCF)
        .replace("{name}", &project.name)
        .replace("{maturity_label}", maturity_label)
        .replace("{full_name}", &project.full_name)
        .replace("{description}", &project.description)
        .replace("{language}", project.language.as_deref().unwrap_or("未知"))
        .replace("{stars}", &format!("{}", project.stars))
        .replace("{accepted_at}", &accepted_str);

    llm.invoke(&prompt)
        .await
        .unwrap_or_else(|e| format!("摘要生成失敗: {}", e))
}

pub async fn summarize_hf_model(model: &HFModel, llm: &LLMClient) -> String {
    use crate::fetcher::huggingface::fmt_num;
    let prompt = decode(enc::HF_MODEL)
        .replace("{model_id}", &model.model_id)
        .replace("{pipeline_tag}", &model.pipeline_tag)
        .replace("{downloads}", &fmt_num(model.downloads))
        .replace("{likes}", &fmt_num(model.likes))
        .replace(
            "{tags}",
            &if model.tags.is_empty() {
                "-".to_string()
            } else {
                model.tags.join(", ")
            },
        );

    llm.invoke(&prompt)
        .await
        .unwrap_or_else(|e| format!("摘要生成失敗: {}", e))
}

pub async fn summarize_podcast(ep: &PodcastEpisode, kw: &str, llm: &LLMClient) -> String {
    let prompt = decode(enc::PODCAST)
        .replace("{keyword}", kw)
        .replace("{podcast_name}", &ep.podcast_name)
        .replace("{title}", &ep.title)
        .replace("{duration}", &ep.duration)
        .replace("{description}", &ep.description);

    llm.invoke(&prompt)
        .await
        .unwrap_or_else(|e| format!("摘要生成失敗: {}", e))
}

pub async fn summarize_release(item: &ReleaseItem, repo: &str, llm: &LLMClient) -> String {
    let date_str = item
        .published
        .map(|d| d.format("%Y-%m-%d").to_string())
        .unwrap_or_else(|| "未知".to_string());

    let body_trimmed = if item.body.trim().is_empty() {
        "（無詳細 Release Notes）".to_string()
    } else {
        item.body.clone()
    };

    let prompt = decode(enc::RELEASE)
        .replace("{repo}", repo)
        .replace("{tag}", &item.tag_name)
        .replace("{name}", &item.name)
        .replace("{date}", &date_str)
        .replace("{body}", &body_trimmed);

    llm.invoke(&prompt)
        .await
        .unwrap_or_else(|e| format!("摘要生成失敗: {}", e))
}

pub async fn analyze_competition(
    target: &Blip,
    all_blips: &[Blip],
    q_names: &HashMap<String, String>,
    kw: &str,
    llm: &LLMClient,
) -> CompetitionAnalysis {
    let today = Utc::now().format("%Y-%m-%d").to_string();
    let ring_desc = match target.ring.as_str() {
        "adopt" => "目前生產環境主流",
        "trial" => "有成功案例，值得在新專案採用",
        "assess" => "值得關注，仍在快速發展",
        "hold" => "建議暫緩，有更好替代方案",
        _ => "",
    };
    let oss_label = if target.is_open_source {
        "類型：開源"
    } else {
        "類型：閉源"
    };
    let q_label = q_names
        .get(&target.quadrant)
        .cloned()
        .unwrap_or_else(|| target.quadrant.clone());
    let radar_items = build_radar_items(target, all_blips);

    let prompt_json = decode(enc::COMPETITOR_JSON)
        .replace("{name}", &target.name)
        .replace("{keyword}", kw)
        .replace("{description}", &target.description)
        .replace("{radar_items}", &radar_items);

    let prompt_text = decode(enc::ANALYSIS_TEXT)
        .replace("{today}", &today)
        .replace("{keyword}", kw)
        .replace("{name}", &target.name)
        .replace("{ring_upper}", &target.ring.to_uppercase())
        .replace("{ring_desc}", ring_desc)
        .replace("{quadrant}", &q_label)
        .replace("{oss_label}", oss_label)
        .replace("{description}", &target.description)
        .replace("{pros}", &target.pros.join("、"))
        .replace("{cons}", &target.cons.join("、"))
        .replace("{radar_items}", &radar_items);

    // Two parallel LLM calls
    let (json_result, text_result) = tokio::join!(
        llm.invoke(&prompt_json),
        llm.invoke_with_limit(&prompt_text, 4096)
    );

    // Parse competitors JSON
    let competitors = match json_result {
        Ok(ref raw) => {
            let s = strip_code_fence(raw);
            match (s.find('['), s.rfind(']')) {
                (Some(start), Some(end)) => {
                    serde_json::from_str::<Vec<CompetitorRow>>(&s[start..=end]).unwrap_or_default()
                }
                _ => vec![],
            }
        }
        Err(_) => vec![],
    };

    let text = text_result.unwrap_or_else(|e| format!("分析生成失敗: {}", e));

    CompetitionAnalysis { competitors, text }
}
